version: "3.0"

services:
  ui:
    build: "FE"
    depends_on: [ "widget-manager" ]
    ports: ["8081:80"]
  widget-manager:
    build: "BE/widget-manager"
  proxy:
    build: "proxy"
    ports: ["8080:80"]